# Generated by Django 4.2.19 on 2025-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.BinaryField(editable=True),
        ),
    ]
