# Generated by Django 4.2.19 on 2025-03-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_main_image_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.BinaryField(editable=True),
        ),
    ]
